# .readthedocs.yaml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

conda:
   environment: docs/environment.yaml

sphinx:
   configuration: docs/conf.py

submodules:
   include: all 

build:
   os: "ubuntu-24.04"
   tools:
      python: "miniforge3-25.11"
   jobs:
      post_create_environment:
         # Install the package in editable mode so autoapi can import it
         - pip install -e .