# The regex used is a bit different from original documenation:
# https://docs.conda.io/projects/conda-build/en/latest/resources/define-metadata.html#loading-data-from-other-files
# Original documentation implies that the __init__.py only has one line with __version__
---
{% set version_match = load_file_regex(load_file="maxent_disaggregation/__init__.py", 
regex_pattern='(?:.*)__version__ = "(.+)"') %}

{% set version = version_match[1] %}


package:
        name: maxent_disaggregation
        version: {{ version }}

source:
        git_url: ../

requirements:
        build:
                - python
                - setuptools
        host:
                - python>=3.9, <3.14
                - pip
                - numpy
                - scipy
                - nlopt
        run:
                - python>=3.9, <3.14
                - pip
                - numpy
                - scipy
                - matplotlib
                - nlopt
        

about:
        home: https://github.com/jakobsarthur/maxent_disaggregation
        license: MIT
        license_file: LICENSE

build:
        noarch: python
        script: {{ PYTHON }} -m pip install --no-deps --no-build-isolation . -vv
