---
name: Build and deploy conda package

on:
  push:
    branches: [main, develop]
    tags: '*'
    paths-ignore:
      # Don't re-build if we only change README.md Or CHANGES.md
      - '**.md'
jobs:
  conda-pkg-build:
    name: build
    runs-on: "ubuntu-latest"
    defaults:
      run:
        shell: bash -el {0}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: conda-incubator/setup-miniconda@v3
        with:
          python-version: 3.12
          auto-activate-base: true
      - name: Publish distribution 📦 to conda channels
        if: startsWith(github.ref, 'refs/tags')
        env:
          ANACONDA_API_TOKEN: ${{ secrets.ANACONDA_TOKEN }}
        run: |
          conda info
          conda config --set auto_update_conda False
          conda install -y -q conda-build anaconda-client conda-index
          ls -la
          ls -la conda/
          conda build ./conda --output-folder ./conda-out
          anaconda -t $ANACONDA_API_TOKEN upload ./conda-out/*/maxent_disaggregation-*.conda
